### PR TITLE
Update dev setup instructions

### PR DESCRIPTION
**Pull request by blancadesal**
Some updates to the instructions on how to set up a local dev environment.

### CODE REVIEW

**Comment by david-caro** [comment]
LGTM :+1:

**Comment by david-caro** [comment]
Let me know if you want to continue building up on this, or we should merge.

**Comment by blancadesal** [comment]
Let's leave it open for now, I'm experimenting with a slightly different dev setup right now, without Docker for Desktop.

**Comment by blancadesal** [comment]
Closing this PR, as there have been numerous changes since, and it's no longer relevant.

**Pull request closed without merging**
