### PR TITLE
Upgrade harbor to 2.5.4

### PR DESCRIPTION
**Pull request by david-caro**
Bug: T316530

### CODE REVIEW

**Comment by david-caro** [comment]
I can split the readme if needed to a different PR

**Comment by blancadesal** [comment]
> I can split the readme if needed to a different PR

I think it's ok to leave it here

**Review by dhinus — APPROVED** [review]
I'm fine with including the README changes as well.

:shipit:

**Review by blancadesal — APPROVED** [review]

**Comment by david-caro** [comment]
@NdibeRaymond I'll leave the proper testing and prod changes for you ;)

**Comment by NdibeRaymond** [comment]
> @NdibeRaymond I'll leave the proper testing and prod changes for you ;)

deployed this on `toolsbeta control node` without any issues. When I changed the version on puppet and applied to `toolsbeta-harbor-1`, I noticed that it sometimes complain about docker and kubernetes (although this happens even with the previous version). The interesting thing is that it stopped (or the frequency reduced) after I ran through the process of install docker-ce -> run-puppet-agent -> uninstall docker-ce several times. I thought puppet was supposed to enforce idempotency?

also was able to build image on toolsbeta-sgebastion-05 but before it could export to harbor it threw the error
`[build-from-git : export] ERROR: failed to export: failed to write image to the following tags: [harbor.toolsbeta.wmflabs.org/raymond-ndibe/raymond-ndibe:latest: HEAD https://harbor.toolsbeta.wmflabs.org/v2/raymond-ndibe/raymond-ndibe/blobs/sha256:6924f3c220b3bc894d1a1759ec3cfd4be662466110e1980a383110ac75b3fe4e: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)]
`
my understanding is that the error above was because of some permission issues but I'm dropping it here just in case I am wrong

**Review by NdibeRaymond — APPROVED** [review]

**Comment by david-caro** [comment]
> also was able to build image on toolsbeta-sgebastion-05 but before it could export to harbor it threw the error
> `[build-from-git : export] ERROR: failed to export: failed to write image to the following tags: [harbor.toolsbeta.wmflabs.org/raymond-ndibe/raymond-ndibe:latest: HEAD https://harbor.toolsbeta.wmflabs.org/v2/raymond-ndibe/raymond-ndibe/blobs/sha256:6924f3c220b3bc894d1a1759ec3cfd4be662466110e1980a383110ac75b3fe4e: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)] `
> my understanding is that the error above was because of some permission issues but I'm dropping it here just in case I am wrong

This is because your project does not exist yet in harbor (just manually created, will be automatically created when we fix the maintainkubeusers script to do so), can you try again?

**Comment by david-caro** [comment]
Actually, I got this error too with the toolsbeta.test account:
```
[build-from-git : export]       harbor.toolsbeta.wmflabs.org/test/python:snap - POST https://harbor.toolsbeta.wmflabs.org/v2/test/python/blobs/uploads/: UNAUTHORIZED: unauthorized to access repository: test/python, action: push: unauthorized to access repository: test/python, action: push
```
And the issue was that the basic-user-pass secret (the file `deploy/toolsbeta/auth-patch.yaml`) was deployed without changing the "PLACEHOLDER" value for the user and pass.

After changing that, I get the error:
```
[build-from-git : export]       harbor.toolsbeta.wmflabs.org/test/python:snap - POST https://harbor.toolsbeta.wmflabs.org/v2/test/python/blobs/uploads/: UNKNOWN: unknown er
ror; map[DriverName:filesystem Enclosed:map[Err:13 Op:mkdir Path:/storage/docker/registry/v2/repositories/test/python/_uploads/a8e6b3eb-3381-4488-91dc-31eba9de1e79]]
```

That points to it being unable to created the directory /storage/docker/registry/v2/repositories/test/python/_uploads/a8e6b3eb-3381-4488-91dc-31eba9de1e79] on harbor side, probably a leftover from me moving from one host to the other, looking

**Pull request merged**
